{
    'name': "OSchool Single Company",
    'version': '1.0',
    'sequence':1,
    'depends': ['hr', 'point_of_sale', 'account_accountant', 'l10n_tn','treasury'],
    'author': "WHITECAPE TECHNOLOGY",
    'category': 'OSchool',
    'description': """
        A module to School Management.
        A Module support the following functionalities:
    """,
    # data files always loaded at installation
    'data': [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/init_data.xml",
        "views/config_menus.xml",
         #From sofien
        "oschool_extra/product_data.xml",
        "oschool_responsible/oschool_responsible_view.xml",
        "oschool_responsible/responsible_sequence.xml",
        "oschool_responsible/wizard/oschool_responsible_payment_view.xml",
        "oschool_responsible/report/responsible_report_view.xml",
        "oschool_student/oschool_student_view.xml",
        "oschool_student/student_relationship_view.xml",
        "oschool_student/relationship_data.xml",
        "oschool_student/student_sequence.xml",
        "oschool_extra/wizard/oschool_extra_wizard_view.xml",
        "oschool_extra/oschool_payment_view.xml",
        "oschool_extra/oschool_extra_view.xml",
        "oschool_registration/oschool_registration_view.xml",
        "oschool_registration/oschool_payment_view.xml",
        # "oschool_cashier/oschool_cashier_view.xml",
        "oschool_study/wizard/oschool_study_wizard_view.xml",
        "oschool_study/oschool_payment_view.xml",
        "oschool_study/oschool_study_student_view.xml",
        "oschool_transportation/wizard/oschool_transport_view.xml",
        "oschool_transportation/oschool_transportation_student_view.xml",
        "oschool_transportation/oschool_payment_view.xml",
        "oschool_service/wizard/oschool_service_generate_view.xml",
        "oschool_service/oschool_payment_view.xml",
        "oschool_service/oschool_service_student_view.xml",
        "oschool_club/oschool_payment_view.xml",
        "oschool_club/oschool_club_student_view.xml",
        "oschool_club/wizard/oschool_club_generate_view.xml",
        #From WCT
        "views/groups.xml",
        "views/classes.xml",
        "views/parents_categories.xml",
        "views/oschool_product_quantity_view.xml",
        "views/oschool_pos_payement_view.xml",
        "views/oschool_account_journal_view.xml",
        "oschool_academic_year/oschool_fiscal_year_view.xml",
        "oschool_academic_year/oschool_academic_year_view.xml",
        "oschool_study/oschool_study_view.xml",
        "oschool_service/oschool_service_view.xml",
        "oschool_inscription/oschool_inscription_view.xml",
        "oschool_club/oschool_club_view.xml",
        "oschool_club/oschool_club_presence_status_view.xml",
        "oschool_event/oschool_event_view.xml",
        "oschool_event/oschool_event_registration_view.xml",
        "oschool_transportation/oschool_zone_view.xml",
        "oschool_transportation/oschool_bus_view.xml",
        "oschool_transportation/oschool_route_view.xml",
        "oschool_transportation/oschool_hostess_view.xml",
        "oschool_transportation/oschool_driver_view.xml",
        "oschool_transportation/oschool_affect_bus_to_zone_view.xml",
        "oschool_transportation/oschool_driver_hostess_assignment_view.xml",
        "oschool_transportation/oschool_transport_presence_status_view.xml",
        "oschool_service/oschool_restaurant_presence_status_view.xml",
        "oschool_service/oschool_canteen_presence_status_view.xml",
        "oschool_service/oschool_ticket_presence_status_view.xml",
        "oschool_access_right/oschool_access_group_view.xml",
        "oschool_access_right/oschool_access_user_view.xml",
        "oschool_tracking_registrations/oschool_tracking_registrations_view.xml",
        "oschool_tracking_registrations/oschool_tracking_registrations_cashier_view.xml",
        "oschool_tracking_registrations/oschool_student_statistics_view.xml",
        "oschool_daily_operations/oschool_all_sessions_view.xml",
        "oschool_daily_operations/oschool_orders_view.xml",
        "oschool_daily_operations/oschool_cashier_orders_view.xml",
        "oschool_daily_operations/oschool_session_view.xml",
        "oschool_daily_operations/oschool_pos_config_view.xml",
        "oschool_daily_operations/oschool_pos_payement.xml",
        'oschool_daily_operations/oschool_payment_refund_view.xml',
        "oschool_treasury/oschool_treasury_view.xml",
        "views/oschool.xml",
        "oschool_configuration/oschool_configuration_view.xml",
        'oschool_tracking_payment/oschool_tracking_payment_view.xml',
        "oschool_abstract/res_company_view.xml",
        "oschool_refund_multiple_subscription/oschool_refund_multiple_subscription_view.xml",
        #attandence report
        'reports/oschool_attendance_report/transport.xml',
        'reports/oschool_attendance_report/report_transport.xml',
        'reports/oschool_attendance_report/restaurant.xml',
        'reports/oschool_attendance_report/report_restaurant.xml',
        'reports/oschool_attendance_report/canteen.xml',
        'reports/oschool_attendance_report/report_canteen.xml',
        'reports/oschool_attendance_report/ticket.xml',
        'reports/oschool_attendance_report/report_ticket.xml',
        #pos order reports
        'reports/pos_order/today_payment_report.xml',
        'reports/pos_order/today_payment.xml',
        'reports/registration_recipt/registration_recipt.xml',
        'reports/registration_recipt/report_registration_recipt.xml',
        'reports/registration_recipt/order_button_print.xml',
        #cashbook_report
        'reports/oschool_cashbook_report/cashbook.xml',
        'reports/oschool_cashbook_report/cashbook_report.xml',
        #payment_report
        'reports/payment_report/payment.xml',
        'reports/payment_report/payment_report.xml',
    ],
    'qweb': [
        'static/src/xml/oschool_student_transport_presence_quickadd.xml',
        'static/src/xml/oschool_student_service_presence_quickadd.xml',
        'static/src/xml/oschool_student_club_presence_quickadd.xml',
    ],
    # data files containing optionally loaded demonstration data
    'demo': [
        # 'demo_data.xml',
    ],
    'installable': True,
    'application': True,
}